import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  primaryLight: '#DBEAFE',
  background: '#F4F7FB',
  white: '#FFFFFF',
  text: '#111827',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  border: '#E5E7EB',
  statCardBg: '#EFF6FF',
  statCardBorder: '#DBEAFE',
  sectionMorning: '#F59E0B',
  sectionNoon: '#2563EB',
  sectionEvening: '#6366F1',
  sectionAsNeeded: '#8B5CF6',
  cardAccent: '#2563EB',
  cardAccentSkipped: '#EF4444',
  cardIconBg: '#DBEAFE',
  takenBadgeBg: '#D1FAE5',
  takenBadgeText: '#059669',
  skippedBadgeBg: '#FEE2E2',
  skippedBadgeText: '#DC2626',
  pendingBg: '#F0F9FF',
  pendingBorder: '#93C5FD',
  motivationBg: '#EFF6FF',
  motivationIconBg: '#FFFFFF',
  calendarActive: '#1E3A8A',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingBottom: 16,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerPillIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.text,
  },
  headerTitleAccent: {
    color: COLORS.primary,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 6,
  },
  pageSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
    marginBottom: 20,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.statCardBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.statCardBorder,
    padding: 16,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  statValue: {
    fontSize: 28,
    fontWeight: '800',
    color: COLORS.primary,
  },
  statUnit: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primary,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  calendarMonth: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  calendarLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  calendarLinkText: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.primary,
  },
  calendarCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginBottom: 24,
  },
  calendarRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarDay: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  calendarDayLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  calendarDayLabelActive: {
    color: COLORS.primary,
  },
  calendarDate: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarDateActive: {
    backgroundColor: COLORS.calendarActive,
  },
  calendarDateText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
  },
  calendarDateTextActive: {
    color: COLORS.white,
  },
  calendarDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.white,
    marginTop: -2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginBottom: 12,
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  sectionTimeRange: {
    fontSize: 11,
    fontWeight: '500',
    color: COLORS.textMuted,
  },
  medCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
  },
  medCardPending: {
    backgroundColor: COLORS.pendingBg,
    borderStyle: 'dashed',
    borderColor: COLORS.pendingBorder,
  },
  medCardPressable: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  medCardAccent: {
    width: 4,
    alignSelf: 'stretch',
    backgroundColor: COLORS.cardAccent,
  },
  medCardAccentSkipped: {
    backgroundColor: COLORS.cardAccentSkipped,
  },
  medIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.cardIconBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 14,
    marginRight: 12,
  },
  medInfo: {
    flex: 1,
    paddingVertical: 16,
  },
  medName: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 4,
  },
  medDetail: {
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  medAction: {
    alignItems: 'flex-end',
    paddingRight: 16,
    paddingVertical: 12,
    minWidth: 100,
  },
  takenBadge: {
    backgroundColor: COLORS.takenBadgeBg,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 4,
  },
  takenBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.takenBadgeText,
  },
  takenTimeText: {
    fontSize: 10,
    color: COLORS.textMuted,
    textAlign: 'right',
  },
  skippedBadge: {
    backgroundColor: COLORS.skippedBadgeBg,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 4,
  },
  skippedBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.skippedBadgeText,
  },
  takeNowText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.primary,
  },
  takeButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  takeButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.white,
  },
  motivationCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.motivationBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.statCardBorder,
    padding: 16,
    marginTop: 8,
    gap: 14,
    alignItems: 'flex-start',
  },
  motivationIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.motivationIconBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.statCardBorder,
  },
  motivationContent: {
    flex: 1,
  },
  motivationTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 4,
  },
  motivationText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 19,
  },
  emptyState: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 24,
    alignItems: 'center',
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 32,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 20,
    textAlign: 'center',
  },
  pickerRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  pickerColumn: {
    flex: 1,
    maxHeight: 160,
  },
  pickerItem: {
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  pickerItemActive: {
    backgroundColor: COLORS.primaryLight,
  },
  pickerItemText: {
    fontSize: 16,
    color: COLORS.textSecondary,
  },
  pickerItemTextActive: {
    color: COLORS.primary,
    fontWeight: '700',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },
  modalButtonSecondary: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  modalButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.white,
  },
  modalButtonTextSecondary: {
    color: COLORS.textSecondary,
  },
});

export default styles;
